services:
  - type: worker
    name: brasil-burger-java-console
    env: java
    region: frankfurt
    plan: free
    buildCommand: mvn clean compile
    startCommand: mvn exec:java -Dexec.mainClass="com.brasilburger.Main"
    envVars:
      - key: JAVA_VERSION
        value: "17"
      - key: NEONDB_CONNECTION_STRING
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false