# ============================================
# CONFIGURATION NEONDB CLOUD
# ============================================

# NeonDB PostgreSQL (Cloud)
db.url=jdbc:postgresql://ep-delicate-rice-abdkwyv8-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
db.username=neondb_owner
db.password=npg_rye49YnfuBDX
db.pool.size=5

# Cloudinary RÉEL (tes clés API)
cloudinary.cloud_name=dbdv92yxp
cloudinary.api_key=687693711671779
cloudinary.api_secret=EUGGfr60GtHoF7sDOx2anBkB_is
cloudinary.secure=true

# Application Configuration
app.name=Brasil Burger Java Console - NeonDB Mode
app.version=1.0.0
app.environment=production
app.debug=false

# Console Configuration
console.encoding=UTF-8
console.width=80